### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by hrqmonteiro** [withfig/gnome-shell-extension#1]
You didn't provide any information...

I installed the extension but it only shows an icon with an 'x' on the tray:

![image](https://user-images.githubusercontent.com/17055027/188277641-7cd4cc47-d50e-4839-b9cc-6c93850c208a.png)

So how do i make it work? Because, as far as i am concerned, Fig still doesnt work on Linux, right?

**Comment by grant0417** [comment]
Hey @hrqmonteiro, the extension is usually automatically installed when you install Fig. You can install Fig on Linux by following the instructions here https://fig.io/user-manual/linux
