### ISSUE TITLE
I was using it like a month ago and everything was working fine, not nothing works

### ISSUE THREAD

**Issue by hrqmonteiro** [withfig/gnome-shell-extension#2]
![image](https://user-images.githubusercontent.com/17055027/218877580-7f81a645-4088-463d-9f52-a03835c647b3.png)
![image](https://user-images.githubusercontent.com/17055027/218877642-3324bcef-403b-4749-ad14-5d2124845f4d.png)

I was using Autocomplete normally, and now nothing works. Why?

**Comment by grant0417** [comment]
Are you ssh onto a machine? It may not work 100% in this case, make sure to check these docs: https://fig.io/user-manual/autocomplete/ssh

**Comment by hrqmonteiro** [comment]
I am not.. this is my own machine.
